### Buscar CEP válido
GET http://localhost:8080/69402289
Content-Type: application/json

### Buscar CEP inválido
GET http://localhost:8080/1234567890

### Buscar CEP  válido mas inexistente
GET http://localhost:8080/08556111
Content-Type: application/json

### Buscar CEP válido mas cidade(Poá) não considerada válida na API da weatherapi.com
GET http://localhost:8080/08556450
Content-Type: application/json



### Buscar CEP válido
GET https://lab-goexpert-1-392400719582.southamerica-east1.run.app/69402289
Content-Type: application/json

### Buscar CEP inválido
GET https://lab-goexpert-1-392400719582.southamerica-east1.run.app/1234567890

### Buscar CEP válido mas inexistente
GET https://lab-goexpert-1-392400719582.southamerica-east1.run.app/08556111
Content-Type: application/json

### Buscar CEP válido mas cidade(Poá) não considerada válida na API da weatherapi.com
GET https://lab-goexpert-1-392400719582.southamerica-east1.run.app/08556450
Content-Type: application/json